@startuml
skinparam linetype ortho
skinparam entity {
  BackgroundColor<<FK>> LightYellow
}

entity Users {
  *id
  telefono
  nombre
  apellido
}

entity Roles {
  *id
  name
}

entity UserRoles {
  *user_id
  *role_id
}

entity Categorias {
  *id
  nombre
}

entity Items {
  *id
  nombre
  categoria_id <<FK>>
  user_id <<FK>>
}

entity Opiniones {
  *id
  item_id <<FK>>
}

entity Kardex {
  *id
  item_id <<FK>>
}

entity Reservas {
  *id
  user_id <<FK>>
}

entity Bloques {
  *id
  reserva_id <<FK>>
}

entity ReservaItems {
  *reserva_id
  *item_id
}

entity Ordenes {
  *id
  user_id <<FK>>
}

entity OrdenItems {
  *orden_id
  *item_id
}

entity Empresas {
  *id
  nombre
}

entity ApiTokens {
  *id
  empresa_id <<FK>>
}

entity Difuciones {
  *id
  user_id <<FK>>
}

entity Seguimiento {
  *id
  user_id <<FK>>
}

' -------------------------------
' Relaciones entre entidades
' -------------------------------

Users ||--o{ UserRoles
Roles ||--o{ UserRoles

Categorias ||--o{ Items
Users ||--o{ Items
Items ||--o{ Opiniones
Items ||--o{ Kardex

Users ||--o{ Reservas
Reservas ||--o{ Bloques
Reservas ||--o{ ReservaItems
Items ||--o{ ReservaItems

Users ||--o{ Ordenes
Ordenes ||--o{ OrdenItems
Items ||--o{ OrdenItems

Empresas ||--o{ ApiTokens

Users ||--o{ Difuciones
Users ||--o{ Seguimiento

@enduml
